# Generated by Django 5.1.2 on 2024-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='confirmPw',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
