# Generated by Django 5.1.2 on 2024-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djos',
            name='descrbtion',
            field=models.TextField(default='old dojo'),
        ),
    ]
